---

- name: Set external_url in gitlab.rb
  ansible.builtin.lineinfile:
    path: /etc/gitlab/gitlab.rb
    regexp: "^external_url 'http://.*"
    line: "external_url '{{ gitlab_config_external_url }}'"
    state: present

- name: Set puma port in gitlab.rb
  ansible.builtin.lineinfile:
    path: /etc/gitlab/gitlab.rb
    line: "puma['port'] = {{ gitlab_config_port }}"
    insertafter: "^external_url" 


- name: Reconfigure GitLab
  ansible.builtin.command: gitlab-ctl reconfigure

- name: Restart puma
  ansible.builtin.command: gitlab-ctl restart puma

- name: Restart Gitlab
  ansible.builtin.command: gitlab-ctl restart
