stages:
  - install
  - test
  - run

variables:
  NODE_VERSION: "14.17.0"
  NPM_VERSION: "6.14.13"

before_script:
  - apt-get update -y
  - apt-get install -y curl
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
  - export NVM_DIR="$HOME/.nvm"
  - [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  - nvm alias default $NODE_VERSION
  - npm install -g npm@$NPM_VERSION

install_dependencies:
  stage: install
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

run_tests:
  stage: test
  script:
    - npm test

run_project:
  stage: run
  script:
    - npm start
  artifacts:
    paths:
      - dist/