stages:
  - build

variables:
  BACKEND_DIR: "/home/vagrant/e4l/lu.uni.e4l.platform.api.dev"
  FRONTEND_DIR: "/home/vagrant/e4l/lu.uni.e4l.platform.frontend.dev"
  DB_URL: "jdbc:mysql://localhost:3306/e4l"
  DB_USERNAME: "root"
  DB_PASSWORD: "12345678"
  GRADLE_VERSION: "8.3"
  NODE_VERSION: "15.14.0"
  NPM_VERSION: "7.7.6"

build_backend:
  stage: build
  image: openjdk:20
  script:
    - cd ${BACKEND_DIR}
    - ./gradlew clean build
    - echo "Backend build complete."

build_frontend:
  stage: build
  image: node:15
  script:
    - cd ${FRONTEND_DIR}
    - npm install
    - npm run build
    - echo "Frontend build complete."
