---

- hosts: all
  remote_user: vagrant
  become: yes
  become_method: sudo
    
  vars:
    vHome: /home/vagrant

    # Vars that I added
    integration_ip: 192.168.56.5
    port_guest: 8088
    project_dir: "{{ vHome }}/e4l"
    
    gitlab_user_username: user
    gitlab_user_email: user@example.com
    gitlab_user_name: "user user"
    gitlab_user_password: password
    gitlab_url: "http://{{ integration_ip }}/gitlab/"
    
    #gitlab_token_name: "CI/CD Token"
    #gitlab_token: "AvuTEsPPoPo7_cd5a9EQ" # Replace with the actual token generation mechanism
    #gitlab_repo_remote: "{{ gitlab_project_url }}"

  tasks:

    # Gitlab configuration
    - include_role:
        name: gitlab

    # Docker configuration
    - include_role:
        name: docker
    
    # Gitlab Runner setup
    - include_role:
        name: gitlab_runner
