---

- name: Download Gitlab Runner
  ansible.builtin.command:
    cmd: "curl -L https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh | sudo bash"
    
- name: Install GitLab Runner
  ansible.builtin.command: gitlab-runner

- name: Register Runner
  ansible.builtin.command: gitlab-runner register

  - name: Reset GitLab root password using Rails
  ansible.builtin.shell: |
    sudo gitlab-rails console <<EOF
    user = User.find_by_username('root')
    user.password = 'vagrant1234'
    user.password_confirmation = 'vagrant1234'
    user.save!
    EOF

- name: Create GitLab User
      ansible.builtin.shell: |
        sudo gitlab-rails console <<EOF
        u = User.new(
          username: 'user3',
          email: 'user3@example.com',
          name: 'User 3',
          password: 'vagrant1234',
          password_confirmation: 'vagrant1234'
        )
        u.assign_personal_namespace(Organizations::Organization.default_organization)
        u.skip_confirmation! # Skip confirmation if desired
        u.save!
        EOF

- name: Register GitLab Runner
      ansible.builtin.shell: |
        gitlab-runner register --non-interactive \
          --url {{ API_URL_INTEGRATION }} \
          --registration-token {{ TOKEN }} \
          --description "[integration-server] docker" \
          --tag-list "integration" \
          --executor "docker" \
          --docker-image "ubuntu:22.04"
