---

- name: Download Gitlab Runner
  ansible.builtin.command:
    cmd: "curl -L https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh | sudo bash"
    
- name: Install GitLab Runner
  ansible.builtin.command: gitlab-runner

- name: Register Runner
  ansible.builtin.command: gitlab-runner register

- name: Register Runner for user1
  ansible.builtin.command: >
    gitlab-runner register --non-interactive --url {{ API_URL_INTEGRATION }} --registration-token $(sed -n '1p' /vagrant_data/shared/personal_token.txt) --executor "shell" --description "user1-runner"

- name: Register Runner for user2
  ansible.builtin.command: >
    gitlab-runner register --non-interactive --url {{ API_URL_INTEGRATION }}} --registration-token $(sed -n '2p' /vagrant_data/shared/personal_token.txt) --executor "shell" --description "user2-runner"