---

- name: Add GitLab Runner repository
  shell: curl -L https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh | sudo bash
  become: yes

- name: Install GitLab Runner
  apt:
    name: gitlab-runner
    state: present
  become: yes

- name: Register the GitLab Runner
  become: yes
  shell: |
    sudo gitlab-runner register --non-interactive \
      --url http://192.168.56.5/gitlab/ \
      --registration-token AvuTEsPPoPo7_cd5a9EQ \
      --description "[integration-server] docker" \
      --tag-list "integration" \
      --executor "docker" \
      --docker-image "alpine:latest" \
      --run-untagged="true"

- name: Restart GitLab Runner
  command: sudo gitlab-runner restart