# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|


  '''
  INTEGRATION ENVIRONMENT

  '''

  config.vm.define "integration" do |integration|
    integration.vm.box = "ubuntu/jammy64"
    integration.vm.hostname = "integration"

    # Private network for integration
    integration.vm.network "private_network", ip: "192.168.56.12" # Integration IP
    integration.vm.network "forwarded_port", guest: 8088, host: 8089 # GitLab service port

    # Sync folders
    integration.vm.synced_folder "../../data", "/vagrant_data"

    # VirtualBox configuration
    integration.vm.provider "virtualbox" do |vb|
      vb.memory = "5440"
      vb.cpus = 4
    end

    # Provisioning using Ansible for integration
    integration.vm.provision "ansible" do |ansible|
      ansible.playbook = "./playbook/integration_setup.yml"
    end

    integration.vm.provision "shell", path: "../../data/scripts/gitlab_integration.sh"


  end

end
