---

- name: Download Gitlab Runner
  ansible.builtin.command:
    cmd: "curl -L https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh | sudo bash"
    
- name: Install GitLab Runner
  ansible.builtin.command: gitlab-runner

- name: Register Runner
  ansible.builtin.command: gitlab-runner register