# Basic package list for installation
BASIC_PACKAGES:
  - curl
  - software-properties-common
  - apt-transport-https
  - ca-certificates
  - gnupg-agent
  - build-essential
  - python3
  - make
  - wget
  - unzip
  - dpkg

# Java and Gradle versions
JDK_VERSION: "20"
GRADLE_VERSION: "8.3"

# Node.js and npm versions
NODE_VERSION: "15.14.0"
NPM_VERSION: "7.7.6"

# Database configuration
DB_URL: "jdbc:mysql://localhost:3306/e4l"
DB_USERNAME: "root"
DB_PASSWORD: "12345678"

# Backend configuration
BACKEND_IP: "192.168.56.10"
FRONTED_PORT: 3010
BACKEND_DIR: /home/vagrant/e4l/lu.uni.e4l.platform.api.dev

# Frontend configuration
FRONTEND_IP: "192.168.56.11"
FRONTED_PORT: 8088
API_URL: "http://{{ FRONTEND_IP }}:8080/e4lapi/"
FRONTEND_DIR: /home/vagrant/e4l/lu.uni.e4l.platform.frontend.dev

vHome: /home/vagrant
gitlab_config_external_url: http://192.168.58.9/gitlab
gitlab_config_port: 8088
